### ISSUE TITLE
app.open() promise never resolve

### ISSUE THREAD

**Issue by scodeit** [rkamysz/adobe-node#7]
Hello! I'm trying to automate photoshop 20 on Mac os 10.14 , the photoshop opens, but the open promise never resolves.

**Comment by rkamysz** [comment]
Hi @dzxt , I'm sorry that it takes so long but lately I have a very tight plan and not enough time for my private projects. I also do not have access to Adobe applications and it is difficult for me to test changes. Please try this branch `bridge-talk`. Clone it, do `tsc && npm pack` and in your project install it via `npm i ...your_path_to/adobe-node-1.1.4.tgz`. 
+ In `runScript()` now you can pass path to the custom js file and it should be parsed to jsx or jsfl and executed in Adobe App.

Please try it and let me know if it works

**Comment by scodeit** [comment]
Hi, thx, i'll try!
